# auto pack release tag .tar.gz package

name: pack

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - .*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compress action step
        uses: ./ # Uses an action in the root directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        id: compress
        with:
          command: c
          cwd: ../
          files: |
            ./happynmacos
          outPath: happynet-macos-darwin-amd64-Release ${{ GITHUB_REF##*/ }}.tar.gz
          # Use the output from the `compress` step
          #
      - name: Get the output
        run: echo "The output was ${{ steps.compress.outputs.done }}"

      - uses: actions/upload-artifact@v1
        with:
          name: happynet-macos-darwin-amd64-Release ${{ GITHUB_REF##*/ }}.tar.gz
          path: happynet-macos-darwin-amd64-Release ${{ GITHUB_REF##*/ }}.tar.gz

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          release_name: Release ${{ GITHUB_REF##*/ }}
          body: |
            happyn.cc macos client release ${{ github.ref }}
          draft: false
          prerelease: false
